/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exportacao;

import BO.EmpresaBO;
import Validacao.ValidaTudo;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author luizr
 */
public class Jf_Empresa extends javax.swing.JFrame {
    private EmpresaBO EmpresaBO;
    private String action;
    private int cdEmpresaUpdate;
    private ValidaTudo validaTudo;
    /**
     * Creates new form Empresa
     */
    public Jf_Empresa() {
        initComponents();
        this.EmpresaBO = new EmpresaBO();
        this.action = action;
        this.cdEmpresaUpdate = cdEmpresaUpdate;
        this.validaTudo = new ValidaTudo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cadastro_empresa = new javax.swing.JLabel();
        lbl_nm_empresa = new javax.swing.JLabel();
        txt_nm_empresa = new javax.swing.JTextField();
        lbl_cd_cnpj_empresa = new javax.swing.JLabel();
        txt_cd_cnpj_empresa = new javax.swing.JTextField();
        lbl_sg_empresa = new javax.swing.JLabel();
        cmb_sg_empresa = new javax.swing.JComboBox();
        lbl_nm_cidade_empresa = new javax.swing.JLabel();
        txt_nm_cidade_empresa = new javax.swing.JTextField();
        lbl_nm_endereco_empresa = new javax.swing.JLabel();
        txt_nm_endereco_empresa = new javax.swing.JTextField();
        lbl_cd_numero_empresa = new javax.swing.JLabel();
        txt_cd_numero_empresa = new javax.swing.JTextField();
        btn_cadastrar_empresa = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_cadastro_empresa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cadastro_empresa.setText("CADASTRO DE EMPRESA");

        lbl_nm_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nm_empresa.setText("Nome da empresa:");

        txt_nm_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nm_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nm_empresaActionPerformed(evt);
            }
        });

        lbl_cd_cnpj_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cd_cnpj_empresa.setText("CNPJ da empresa:");

        txt_cd_cnpj_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_sg_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_sg_empresa.setText("Estado empresa:");

        cmb_sg_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_sg_empresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        lbl_nm_cidade_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nm_cidade_empresa.setText("Cidade:");

        txt_nm_cidade_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nm_cidade_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nm_cidade_empresaActionPerformed(evt);
            }
        });

        lbl_nm_endereco_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nm_endereco_empresa.setText("Endereco:");

        txt_nm_endereco_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_cd_numero_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cd_numero_empresa.setText("Numero:");

        txt_cd_numero_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_cadastrar_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cadastrar_empresa.setText("CADASTRAR");
        btn_cadastrar_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_empresaActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cd_cnpj_empresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cd_cnpj_empresa)
                        .addGap(206, 206, 206))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nm_empresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nm_empresa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_voltar)
                                .addGap(138, 138, 138)
                                .addComponent(lbl_cadastro_empresa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nm_cidade_empresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nm_cidade_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lbl_sg_empresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_sg_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nm_endereco_empresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nm_endereco_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_cd_numero_empresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cd_numero_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cadastrar_empresa)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltar)
                    .addComponent(lbl_cadastro_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nm_empresa)
                    .addComponent(txt_nm_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cd_cnpj_empresa)
                    .addComponent(txt_cd_cnpj_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_sg_empresa)
                        .addComponent(cmb_sg_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_nm_cidade_empresa)
                        .addComponent(txt_nm_cidade_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nm_endereco_empresa)
                    .addComponent(txt_nm_endereco_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cd_numero_empresa)
                    .addComponent(txt_cd_numero_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btn_cadastrar_empresa)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nm_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nm_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nm_empresaActionPerformed

    private void btn_cadastrar_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_empresaActionPerformed
        String nmEmpresa = txt_nm_empresa.getText(),cdCnpjEmpresa = txt_cd_cnpj_empresa.getText(), 
                            sgEstadoEmpresa = (String) cmb_sg_empresa.getSelectedItem(), 
                                nmCidadeEmpresa = txt_nm_cidade_empresa.getText(), nmEnderecoEmpresa = txt_nm_endereco_empresa.getText();
        String[] parametros = {nmEmpresa, cdCnpjEmpresa,sgEstadoEmpresa, nmCidadeEmpresa, nmEnderecoEmpresa, txt_cd_numero_empresa.getText()};
        String validaEmpresa = this.validaTudo.ValidaEmpresa(parametros);
        if(validaEmpresa == ""){
            int cdNumeroEmpresa = Integer.parseInt(txt_cd_numero_empresa.getText());
            if(this.action == "cadastro"){
                String insert = this.EmpresaBO.insertEmpresa(nmEmpresa, cdCnpjEmpresa, sgEstadoEmpresa, nmCidadeEmpresa, nmEnderecoEmpresa, cdNumeroEmpresa);
                if(insert == "S"){
                    JOptionPane.showMessageDialog(this, "Empresa inserida com sucesso!");
                    txt_nm_empresa.setText("");
                    txt_cd_cnpj_empresa.setText("");
                    txt_nm_cidade_empresa.setText("");
                    txt_nm_endereco_empresa.setText("");
                    txt_cd_numero_empresa.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao inserir empresa");
                }
            }else{
                JOptionPane.showMessageDialog(this, "alteracao" + cdEmpresaUpdate);
            }
        }else{
            JOptionPane.showMessageDialog(this, validaEmpresa);
        }
        
        
    }//GEN-LAST:event_btn_cadastrar_empresaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Jf_IndexInterna cadastro = new Jf_IndexInterna();
        hide();
        cadastro.show();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void txt_nm_cidade_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nm_cidade_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nm_cidade_empresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_Empresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar_empresa;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox cmb_sg_empresa;
    private javax.swing.JLabel lbl_cadastro_empresa;
    private javax.swing.JLabel lbl_cd_cnpj_empresa;
    private javax.swing.JLabel lbl_cd_numero_empresa;
    private javax.swing.JLabel lbl_nm_cidade_empresa;
    private javax.swing.JLabel lbl_nm_empresa;
    private javax.swing.JLabel lbl_nm_endereco_empresa;
    private javax.swing.JLabel lbl_sg_empresa;
    private javax.swing.JTextField txt_cd_cnpj_empresa;
    private javax.swing.JTextField txt_cd_numero_empresa;
    private javax.swing.JTextField txt_nm_cidade_empresa;
    private javax.swing.JTextField txt_nm_empresa;
    private javax.swing.JTextField txt_nm_endereco_empresa;
    // End of variables declaration//GEN-END:variables


    public String acao(String acao, int cdEmpresa) {
        if(acao != "" && cdEmpresa != 0){
            this.action = acao;
            this.cdEmpresaUpdate = cdEmpresa;
            
            return action;
        }else{
            return action;
        }
    }
}
