/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exportacao;

import javax.swing.JOptionPane;

/**
 *
 * @author luizr
 */
public class Jf_IndexInterna extends javax.swing.JFrame {
    private String action;
    /**
     * Creates new form Jf_cadastro
     */
    public Jf_IndexInterna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cadastro_empresa = new javax.swing.JButton();
        btn_cadastro_produto = new javax.swing.JButton();
        btn_cadastro_pedido = new javax.swing.JButton();
        btn_cadastro_armazem = new javax.swing.JButton();
        btn_cadastro_transportadora = new javax.swing.JButton();
        btn_cadastro_porto = new javax.swing.JButton();
        btn_cadastro_navio = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cadastro_empresa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cadastro_empresa.setText("Empresa");
        btn_cadastro_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_empresaActionPerformed(evt);
            }
        });

        btn_cadastro_produto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cadastro_produto.setText("Produto");
        btn_cadastro_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_produtoActionPerformed(evt);
            }
        });

        btn_cadastro_pedido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cadastro_pedido.setText("Pedido");
        btn_cadastro_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_pedidoActionPerformed(evt);
            }
        });

        btn_cadastro_armazem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cadastro_armazem.setText("Armazem");
        btn_cadastro_armazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_armazemActionPerformed(evt);
            }
        });

        btn_cadastro_transportadora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cadastro_transportadora.setText("Transportadora");
        btn_cadastro_transportadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_transportadoraActionPerformed(evt);
            }
        });

        btn_cadastro_porto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cadastro_porto.setText("Porto");
        btn_cadastro_porto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_portoActionPerformed(evt);
            }
        });

        btn_cadastro_navio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cadastro_navio.setText("Navio");
        btn_cadastro_navio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_navioActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cadastro_transportadora, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(btn_cadastro_porto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cadastro_navio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cadastro_armazem, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_voltar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cadastro_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btn_cadastro_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(btn_cadastro_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastro_empresa)
                    .addComponent(btn_cadastro_produto)
                    .addComponent(btn_cadastro_pedido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastro_transportadora)
                    .addComponent(btn_cadastro_navio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastro_armazem)
                    .addComponent(btn_cadastro_porto))
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastro_armazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_armazemActionPerformed
        Jf_Armazem armazem = new Jf_Armazem();
        hide();
        armazem.show();
    }//GEN-LAST:event_btn_cadastro_armazemActionPerformed

    private void btn_cadastro_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_pedidoActionPerformed
        Jf_Pedido pedido = new Jf_Pedido();
        hide();
        pedido.show();
    }//GEN-LAST:event_btn_cadastro_pedidoActionPerformed

    private void btn_cadastro_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_produtoActionPerformed
        Jf_Produto produto = new Jf_Produto();
        hide();
        produto.show();
    }//GEN-LAST:event_btn_cadastro_produtoActionPerformed

    private void btn_cadastro_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_empresaActionPerformed
        String acao = acao("");
        if(acao == "cadastro"){
            Jf_Empresa empresa = new Jf_Empresa();
            empresa.acao("cadastro", 0);
            hide();
            empresa.show();
        }else{
            int cdEmpresa = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite o codigo da empresa que deseja alterar: "));
            Jf_Empresa empresa = new Jf_Empresa();
            empresa.acao("alteracao", cdEmpresa);
            hide();
            empresa.show();
        }
        
    }//GEN-LAST:event_btn_cadastro_empresaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Jf_Opcoes opcoes = new Jf_Opcoes();
        hide();
        opcoes.show();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_cadastro_navioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_navioActionPerformed
        Jf_Navio navio = new Jf_Navio();
        hide();
        navio.show();
    }//GEN-LAST:event_btn_cadastro_navioActionPerformed

    private void btn_cadastro_portoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_portoActionPerformed
        Jf_Porto porto = new Jf_Porto();
        hide();
        porto.show();
    }//GEN-LAST:event_btn_cadastro_portoActionPerformed

    private void btn_cadastro_transportadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_transportadoraActionPerformed
        Jf_Transportadora transportadora = new Jf_Transportadora();
        hide();
        transportadora.show();
    }//GEN-LAST:event_btn_cadastro_transportadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_IndexInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_IndexInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_IndexInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_IndexInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_IndexInterna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastro_armazem;
    private javax.swing.JButton btn_cadastro_empresa;
    private javax.swing.JButton btn_cadastro_navio;
    private javax.swing.JButton btn_cadastro_pedido;
    private javax.swing.JButton btn_cadastro_porto;
    private javax.swing.JButton btn_cadastro_produto;
    private javax.swing.JButton btn_cadastro_transportadora;
    private javax.swing.JButton btn_voltar;
    // End of variables declaration//GEN-END:variables
    public String acao(String acao) {
        if(acao != ""){
            action = acao;
            return action;
        }else{
            return action;
        }
    }
}
