/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exportacao;

/**
 *
 * @author luizr
 */
public class Jf_Nota_Fiscal extends javax.swing.JFrame {

    /**
     * Creates new form Jf_Nota_Fiscal
     */
    public Jf_Nota_Fiscal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        lbl_nota_fiscal = new javax.swing.JLabel();
        cd_pedido_nf = new javax.swing.JLabel();
        cd_nota_fiscal = new javax.swing.JLabel();
        cd_chave_acesso_nf = new javax.swing.JLabel();
        nm_empresa_nf = new javax.swing.JLabel();
        cd_cnpj_empresa = new javax.swing.JLabel();
        sg_estado_empresa_nf = new javax.swing.JLabel();
        nm_cidade_empresa_nf = new javax.swing.JLabel();
        nm_endereco_empresa_nf = new javax.swing.JLabel();
        cd_endereco_empresa_nf = new javax.swing.JLabel();
        cd_produto_nf = new javax.swing.JLabel();
        nm_produto_nf = new javax.swing.JLabel();
        ds_produto_nf = new javax.swing.JLabel();
        nm_porto_nf = new javax.swing.JLabel();
        sg_estado_porto_nf = new javax.swing.JLabel();
        nm_cidade_porto_nf = new javax.swing.JLabel();
        nm_endereco_porto_nf = new javax.swing.JLabel();
        cd_endereco_porto_nf = new javax.swing.JLabel();
        nm_armazem_nf = new javax.swing.JLabel();
        nm_navio_nf = new javax.swing.JLabel();
        dt_saida_navio_nf = new javax.swing.JLabel();
        ds_navio_nf = new javax.swing.JLabel();
        qt_pedido_nf = new javax.swing.JLabel();
        qt_peso_pedido_nf = new javax.swing.JLabel();
        vl_pedido_nf = new javax.swing.JLabel();
        vl_nota_fiscal = new javax.swing.JLabel();
        LBL_1 = new javax.swing.JLabel();
        LBL_2 = new javax.swing.JLabel();
        LBL_3 = new javax.swing.JLabel();
        LBL_4 = new javax.swing.JLabel();
        LBL_5 = new javax.swing.JLabel();
        LBL_6 = new javax.swing.JLabel();
        LBL_7 = new javax.swing.JLabel();
        LBL_8 = new javax.swing.JLabel();
        LBL_9 = new javax.swing.JLabel();
        LBL_10 = new javax.swing.JLabel();
        LBL_11 = new javax.swing.JLabel();
        LBL_12 = new javax.swing.JLabel();
        LBL_13 = new javax.swing.JLabel();
        LBL_14 = new javax.swing.JLabel();
        LBL_15 = new javax.swing.JLabel();
        LBL_16 = new javax.swing.JLabel();
        LBL_17 = new javax.swing.JLabel();
        LBL_18 = new javax.swing.JLabel();
        LBL_19 = new javax.swing.JLabel();
        LBL_20 = new javax.swing.JLabel();
        LBL_21 = new javax.swing.JLabel();
        LBL_22 = new javax.swing.JLabel();
        LBL_23 = new javax.swing.JLabel();
        LBL_24 = new javax.swing.JLabel();
        LBL_25 = new javax.swing.JLabel();
        LBL_26 = new javax.swing.JLabel();
        LBL_27 = new javax.swing.JLabel();
        LBL_28 = new javax.swing.JLabel();
        LBL_29 = new javax.swing.JLabel();
        LBL_30 = new javax.swing.JLabel();
        LBL_31 = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        CODIGO_BARRAS = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nota_fiscal.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_nota_fiscal.setText("NOTA FISCAL");

        cd_pedido_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_pedido_nf.setText("10101010101");

        cd_nota_fiscal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_nota_fiscal.setText("124124125215251");

        cd_chave_acesso_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_chave_acesso_nf.setText("11111111111111111111111111111111111111111111");

        nm_empresa_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_empresa_nf.setText("Yara Brasil LTDA");

        cd_cnpj_empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_cnpj_empresa.setText("99.999.999/9999-99");

        sg_estado_empresa_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sg_estado_empresa_nf.setText("SP");

        nm_cidade_empresa_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_cidade_empresa_nf.setText("Santos");

        nm_endereco_empresa_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_endereco_empresa_nf.setText("Av. Ana Costa");

        cd_endereco_empresa_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_endereco_empresa_nf.setText("100");

        cd_produto_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_produto_nf.setText("10003353222");

        nm_produto_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_produto_nf.setText("Fosfato de amoniaco");

        ds_produto_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ds_produto_nf.setText("Produto Granel feito de açucar e grãos");

        nm_porto_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_porto_nf.setText("SP Santos TUF");

        sg_estado_porto_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sg_estado_porto_nf.setText("SP");

        nm_cidade_porto_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_cidade_porto_nf.setText("Santos");

        nm_endereco_porto_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_endereco_porto_nf.setText("Cais de Santos");

        cd_endereco_porto_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_endereco_porto_nf.setText("100");

        nm_armazem_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_armazem_nf.setText("Armazem Yara Brasil");

        nm_navio_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nm_navio_nf.setText("Power Ranger");

        dt_saida_navio_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dt_saida_navio_nf.setText("28/04/2019");

        ds_navio_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ds_navio_nf.setText("Navio grande, aguenta 400 Toneladas");

        qt_pedido_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qt_pedido_nf.setText("1000,000 TO");

        qt_peso_pedido_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qt_peso_pedido_nf.setText("100,00TO");

        vl_pedido_nf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vl_pedido_nf.setText("10000,00");

        vl_nota_fiscal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vl_nota_fiscal.setText("100,00");

        LBL_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_1.setText("NF-e:");

        LBL_2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_2.setText("Nº:");

        LBL_3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_3.setText("Pedido:");

        LBL_4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_4.setText("Chave de acesso:");

        LBL_5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_5.setText("Valor da nota fiscal:");

        LBL_6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_6.setText("Nome:");

        LBL_7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_7.setText("Cnpj:");

        LBL_8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_8.setText("Estado:");

        LBL_9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_9.setText("Cidade:");

        LBL_10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_10.setText("Endereço:");

        LBL_11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_11.setText("Numero:");

        LBL_12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_12.setText("Código do produto:");

        LBL_13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_13.setText("Nome do produto:");

        LBL_14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_14.setText("Descrição do produto:");

        LBL_15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_15.setText("Nome:");

        LBL_16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_16.setText("Estado:");

        LBL_17.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        LBL_17.setText("Empresa:");

        LBL_18.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        LBL_18.setText("Porto:");

        LBL_19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        LBL_19.setText("Produto:");

        LBL_20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_20.setText("Cidade:");

        LBL_21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_21.setText("Endereço:");

        LBL_22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_22.setText("Numero:");

        LBL_23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_23.setText("Nome do armazem:");

        LBL_24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_24.setText("Descrição do navio:");

        LBL_25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_25.setText("Nome:");

        LBL_26.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        LBL_26.setText("Navio:");

        LBL_27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_27.setText("Data de saida:");

        LBL_28.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        LBL_28.setText("Pedido:");

        LBL_29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_29.setText("Quantidade do produto no pedido:");

        LBL_30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_30.setText("Peso do pedido:");

        LBL_31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBL_31.setText("Valor do pedido:");

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        CODIGO_BARRAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/codigo_barra.JPG"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vl_pedido_nf)
                                .addGap(74, 74, 74)
                                .addComponent(LBL_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vl_nota_fiscal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cd_endereco_empresa_nf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cd_produto_nf)
                                .addGap(70, 70, 70)
                                .addComponent(LBL_13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nm_produto_nf))
                            .addComponent(LBL_19)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ds_produto_nf))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBL_3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cd_pedido_nf))
                                    .addComponent(CODIGO_BARRAS))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBL_2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cd_nota_fiscal))
                                    .addComponent(LBL_1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qt_pedido_nf)
                                .addGap(40, 40, 40)
                                .addComponent(LBL_30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qt_peso_pedido_nf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cd_chave_acesso_nf, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBL_17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBL_6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nm_empresa_nf))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBL_10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nm_endereco_empresa_nf)
                                        .addGap(44, 44, 44)
                                        .addComponent(LBL_9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nm_cidade_empresa_nf)))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBL_7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cd_cnpj_empresa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBL_8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sg_estado_empresa_nf))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LBL_16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sg_estado_porto_nf)
                                .addGap(71, 71, 71)
                                .addComponent(LBL_20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nm_cidade_porto_nf))
                            .addComponent(LBL_18)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nm_porto_nf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nm_armazem_nf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nm_endereco_porto_nf))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(LBL_22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cd_endereco_porto_nf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nm_navio_nf))
                            .addComponent(LBL_28)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ds_navio_nf))
                            .addComponent(LBL_26)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(LBL_27)
                                .addGap(106, 106, 106)
                                .addComponent(dt_saida_navio_nf)))
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_nota_fiscal)
                        .addGap(199, 199, 199)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_voltar)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbl_nota_fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBL_1)
                        .addComponent(cd_pedido_nf))
                    .addComponent(LBL_3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CODIGO_BARRAS, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cd_nota_fiscal))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cd_chave_acesso_nf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(LBL_17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_empresa_nf)
                    .addComponent(cd_cnpj_empresa)
                    .addComponent(LBL_7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_estado_empresa_nf)
                    .addComponent(LBL_9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_cidade_empresa_nf)
                    .addComponent(LBL_10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_endereco_empresa_nf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cd_endereco_empresa_nf)
                    .addComponent(LBL_11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(LBL_19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cd_produto_nf)
                    .addComponent(LBL_12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_produto_nf)
                    .addComponent(LBL_13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ds_produto_nf))
                .addGap(38, 38, 38)
                .addComponent(LBL_18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_porto_nf)
                    .addComponent(LBL_16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sg_estado_porto_nf)
                    .addComponent(LBL_20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_cidade_porto_nf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_endereco_porto_nf)
                    .addComponent(cd_endereco_porto_nf)
                    .addComponent(LBL_22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm_armazem_nf))
                .addGap(31, 31, 31)
                .addComponent(LBL_26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nm_navio_nf)
                    .addComponent(LBL_25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_saida_navio_nf)
                    .addComponent(LBL_27, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ds_navio_nf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(LBL_28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qt_pedido_nf)
                    .addComponent(LBL_29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qt_peso_pedido_nf)
                    .addComponent(LBL_30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_31, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vl_pedido_nf)
                    .addComponent(LBL_5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vl_nota_fiscal))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Jf_Pedido pedido = new Jf_Pedido();
        hide();
        pedido.show();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_Nota_Fiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_Nota_Fiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_Nota_Fiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_Nota_Fiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_Nota_Fiscal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CODIGO_BARRAS;
    private javax.swing.JLabel LBL_1;
    private javax.swing.JLabel LBL_10;
    private javax.swing.JLabel LBL_11;
    private javax.swing.JLabel LBL_12;
    private javax.swing.JLabel LBL_13;
    private javax.swing.JLabel LBL_14;
    private javax.swing.JLabel LBL_15;
    private javax.swing.JLabel LBL_16;
    private javax.swing.JLabel LBL_17;
    private javax.swing.JLabel LBL_18;
    private javax.swing.JLabel LBL_19;
    private javax.swing.JLabel LBL_2;
    private javax.swing.JLabel LBL_20;
    private javax.swing.JLabel LBL_21;
    private javax.swing.JLabel LBL_22;
    private javax.swing.JLabel LBL_23;
    private javax.swing.JLabel LBL_24;
    private javax.swing.JLabel LBL_25;
    private javax.swing.JLabel LBL_26;
    private javax.swing.JLabel LBL_27;
    private javax.swing.JLabel LBL_28;
    private javax.swing.JLabel LBL_29;
    private javax.swing.JLabel LBL_3;
    private javax.swing.JLabel LBL_30;
    private javax.swing.JLabel LBL_31;
    private javax.swing.JLabel LBL_4;
    private javax.swing.JLabel LBL_5;
    private javax.swing.JLabel LBL_6;
    private javax.swing.JLabel LBL_7;
    private javax.swing.JLabel LBL_8;
    private javax.swing.JLabel LBL_9;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel cd_chave_acesso_nf;
    private javax.swing.JLabel cd_cnpj_empresa;
    private javax.swing.JLabel cd_endereco_empresa_nf;
    private javax.swing.JLabel cd_endereco_porto_nf;
    private javax.swing.JLabel cd_nota_fiscal;
    private javax.swing.JLabel cd_pedido_nf;
    private javax.swing.JLabel cd_produto_nf;
    private javax.swing.JLabel ds_navio_nf;
    private javax.swing.JLabel ds_produto_nf;
    private javax.swing.JLabel dt_saida_navio_nf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_nota_fiscal;
    private javax.swing.JLabel nm_armazem_nf;
    private javax.swing.JLabel nm_cidade_empresa_nf;
    private javax.swing.JLabel nm_cidade_porto_nf;
    private javax.swing.JLabel nm_empresa_nf;
    private javax.swing.JLabel nm_endereco_empresa_nf;
    private javax.swing.JLabel nm_endereco_porto_nf;
    private javax.swing.JLabel nm_navio_nf;
    private javax.swing.JLabel nm_porto_nf;
    private javax.swing.JLabel nm_produto_nf;
    private javax.swing.JLabel qt_pedido_nf;
    private javax.swing.JLabel qt_peso_pedido_nf;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JLabel sg_estado_empresa_nf;
    private javax.swing.JLabel sg_estado_porto_nf;
    private javax.swing.JLabel vl_nota_fiscal;
    private javax.swing.JLabel vl_pedido_nf;
    // End of variables declaration//GEN-END:variables
}
