/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exportacao;

/**
 *
 * @author luizr
 */
public class Jf_Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Jf_pedido
     */
    public Jf_Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cadastro_produto = new javax.swing.JLabel();
        lbl_nm_empresa_pedido = new javax.swing.JLabel();
        cmb_nm_empresa_pedido = new javax.swing.JComboBox();
        lbl_cd_produto_pedido = new javax.swing.JLabel();
        cmb_cd_produto_pedido = new javax.swing.JComboBox();
        lbl_cd_carga_pedido = new javax.swing.JLabel();
        cmb_cd_carga_pedido = new javax.swing.JComboBox();
        lbl_nm_navio_pedido = new javax.swing.JLabel();
        cmb_nm_navio_pedido = new javax.swing.JComboBox();
        lbl_qt_produto_pedido = new javax.swing.JLabel();
        txt_qt_produto_pedido = new javax.swing.JTextField();
        lbl_qt_peso_pedido = new javax.swing.JLabel();
        txt_qt_peso_pedido = new javax.swing.JTextField();
        lbl_vl_pedido = new javax.swing.JLabel();
        txt_vl_pedido = new javax.swing.JTextField();
        lbl_dt_pedido = new javax.swing.JLabel();
        txt_dt_pedido = new javax.swing.JTextField();
        btn_cadastrar_pedido = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_cadastro_produto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_cadastro_produto.setText("CADASTRO DO PEDIDO");

        lbl_nm_empresa_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nm_empresa_pedido.setText("Empresa:");

        cmb_nm_empresa_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_nm_empresa_pedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yara" }));

        lbl_cd_produto_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cd_produto_pedido.setText("Produto:");

        cmb_cd_produto_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_cd_produto_pedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Açucar" }));

        lbl_cd_carga_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cd_carga_pedido.setText("Código da carga:");

        cmb_cd_carga_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_cd_carga_pedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yara" }));

        lbl_nm_navio_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nm_navio_pedido.setText("Navio:");

        cmb_nm_navio_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_nm_navio_pedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Power Ranger" }));

        lbl_qt_produto_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_qt_produto_pedido.setText("Quantidade do produto:");

        txt_qt_produto_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_qt_peso_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_qt_peso_pedido.setText("Peso do pedido:");

        txt_qt_peso_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_vl_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_vl_pedido.setText("Valor do pedido:");

        txt_vl_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_dt_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_dt_pedido.setText("Data agendada para saida:");

        txt_dt_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_cadastrar_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cadastrar_pedido.setText("Cadastrar");
        btn_cadastrar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_pedidoActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nm_navio_pedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_nm_navio_pedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cd_produto_pedido)
                            .addComponent(lbl_nm_empresa_pedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_nm_empresa_pedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_cd_produto_pedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cd_carga_pedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_cd_carga_pedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_vl_pedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_vl_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_qt_produto_pedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_qt_produto_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_qt_peso_pedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_qt_peso_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dt_pedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_dt_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_voltar)
                                .addGap(129, 129, 129)
                                .addComponent(lbl_cadastro_produto)))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(btn_cadastrar_pedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastro_produto)
                    .addComponent(btn_voltar))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nm_empresa_pedido)
                    .addComponent(cmb_nm_empresa_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cd_produto_pedido)
                    .addComponent(cmb_cd_produto_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cd_carga_pedido)
                    .addComponent(cmb_cd_carga_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nm_navio_pedido)
                    .addComponent(cmb_nm_navio_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_qt_produto_pedido)
                    .addComponent(txt_qt_produto_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_qt_peso_pedido)
                    .addComponent(txt_qt_peso_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_vl_pedido)
                    .addComponent(txt_vl_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dt_pedido)
                    .addComponent(txt_dt_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn_cadastrar_pedido)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_pedidoActionPerformed
        Jf_Nota_Fiscal nota_fiscal = new Jf_Nota_Fiscal();
        hide();
        nota_fiscal.show();
    }//GEN-LAST:event_btn_cadastrar_pedidoActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Jf_IndexInterna cadastro = new Jf_IndexInterna();
        hide();
        cadastro.show();
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jf_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jf_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jf_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jf_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jf_Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar_pedido;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox cmb_cd_carga_pedido;
    private javax.swing.JComboBox cmb_cd_produto_pedido;
    private javax.swing.JComboBox cmb_nm_empresa_pedido;
    private javax.swing.JComboBox cmb_nm_navio_pedido;
    private javax.swing.JLabel lbl_cadastro_produto;
    private javax.swing.JLabel lbl_cd_carga_pedido;
    private javax.swing.JLabel lbl_cd_produto_pedido;
    private javax.swing.JLabel lbl_dt_pedido;
    private javax.swing.JLabel lbl_nm_empresa_pedido;
    private javax.swing.JLabel lbl_nm_navio_pedido;
    private javax.swing.JLabel lbl_qt_peso_pedido;
    private javax.swing.JLabel lbl_qt_produto_pedido;
    private javax.swing.JLabel lbl_vl_pedido;
    private javax.swing.JTextField txt_dt_pedido;
    private javax.swing.JTextField txt_qt_peso_pedido;
    private javax.swing.JTextField txt_qt_produto_pedido;
    private javax.swing.JTextField txt_vl_pedido;
    // End of variables declaration//GEN-END:variables
}
